import { Wrapper, Container, Day, Time, Period } from "./styles";

function Schedule() {
  return (
    <Wrapper>
      <Container>
        <div title="day">
          <ul>
            <li>
              <Day>
                <p>日</p>
              </Day>
            </li>
            <li>
              <Day>
                <p>一</p>
              </Day>
            </li>
            <li>
              <Day>
                <p>二</p>
              </Day>
            </li>
            <li>
              <Day>
                <p>三</p>
              </Day>
            </li>
            <li>
              <Day>
                <p>四</p>
              </Day>
            </li>
            <li>
              <Day>
                <p>五</p>
              </Day>
            </li>
            <li>
              <Day>
                <p>六</p>
              </Day>
            </li>
          </ul>
        </div>
        <div title="time">
          <div>
            <Time>
              <p>8:00</p>
              <p>|</p> <p>12:00</p>
            </Time>
            <ul>
              <li>
                <Period>早上</Period>
              </li>
              <li>
                <Period>早上</Period>
              </li>
              <li>
                <Period>早上</Period>
              </li>
              <li>
                <Period>早上</Period>
              </li>
              <li>
                <Period>早上</Period>
              </li>
              <li>
                <Period>早上</Period>
              </li>
              <li>
                <Period>早上</Period>
              </li>
            </ul>
          </div>
          <div>
            <Time>
              <p>13:00</p>
              <p>|</p>
              <p>17:00</p>
            </Time>
            <ul>
              <li>
                <Period>下午</Period>
              </li>
              <li>
                <Period>下午</Period>
              </li>
              <li>
                <Period>下午</Period>
              </li>
              <li>
                <Period>下午</Period>
              </li>
              <li>
                <Period>下午</Period>
              </li>
              <li>
                <Period>下午</Period>
              </li>
              <li>
                <Period>下午</Period>
              </li>
            </ul>
          </div>
          <div>
            <Time>
              <p>19:00</p>
              <p>|</p>
              <p>23:00</p>
            </Time>
            <ul>
              <li>
                <Period>晚上</Period>
              </li>
              <li>
                <Period>晚上</Period>
              </li>
              <li>
                <Period>晚上</Period>
              </li>
              <li>
                <Period>晚上</Period>
              </li>
              <li>
                <Period>晚上</Period>
              </li>
              <li>
                <Period>晚上</Period>
              </li>
              <li>
                <Period>晚上</Period>
              </li>
            </ul>
          </div>
        </div>
      </Container>
    </Wrapper>
  );
}

export default Schedule;
